### ISSUE TITLE
...

### ISSUE THREAD

**Issue by moniruzzamanmasud** [masud/flaskblog#1]

**Comment by masud** [comment]
sorry, don't understood, can you please share details?

**Comment by moniruzzamanmasud** [comment]
Thank you vaiya reply deyar jonno.

Amar nam `Masud Rana`. Ami programming niye kaj kori. Recently ami ekti programming language build korechi nam: `@neolang - neo programming language`, github personal account ei ati ache, ekhon organization create korte chacci.

Organization create er jonno github personal account lage (real name as a username is best). Open source `codes` publish korar por news websites and wikipedia te articles publish korte chacci nijer nam er username use kore tahole easily articles approve and community build kora jabe and trusted hobe (github url and nam/username articles e thakbe). In future e programming language developer er info, ex: github account and organisation easily find korte parbe (publicity & popularity jonno).

Ami chacci and request amar j, apnar github username: `masud` eita amak diye din, ami username ti diye github account korbo and organization create korbo (apnar account thikh thakbe, just apnar username ti change korte hobe tahole available hobe and ami nite/set korte parbo).

apnar github profile url: `https://github.com/masud`
just first e or last e kisu add kore dile change hobe, example: `https://github.com/mamasud`

Then username ti available hole ami niye nibo.

Eikhane https://github.com/settings/admin Change Username option paben.

Jodi username diye help koren vaiya ami onek khushi hobo, change er agey must be amak janaben, noyto onno keu niye nibe. R jodi apnar github account ti dite chan tahole kritoggo thakbo. Don't mind, financial help lagle janaben - try korbo khushi korar jonno apnake.

Apnar reply jonno wait korteci, hope so reply will be positive 🙂 thank you vaiya.

**Comment by moniruzzamanmasud** [comment]
@masud don't take pressure bro, just try to understand what i said on above comment, if you don't understand then share your facebook profile link, we will discuss on there. Thank you again.
